project:
  type: website

website:
  title: "test-site"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    background: dark

format:
  html:
    theme: vapor
    css: styles.css
    toc: true

editor: visual

