project:
  type: website

website:
  title: "pls"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: idk.qmd
        text: Hello

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

